"""Add has_completed_tour to users

Revision ID: 12b7b80a9b6c
Revises: a438085fcc89
Create Date: 2026-07-22 15:53:46.314128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b7b80a9b6c'
down_revision: Union[str, Sequence[str], None] = 'a438085fcc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_tour', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('income_range', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'has_completed_tour')
    op.alter_column('transactions', 'corrected_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('transactions', 'auto_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'has_completed_tour')
    # ### end Alembic commands ###
