"""phase15_schema_expansion

Revision ID: 56d093b8c7b2
Revises: 48be097be811
Create Date: 2026-04-28 17:23:05.802531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d093b8c7b2'
down_revision: Union[str, Sequence[str], None] = '48be097be811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('merchant_key', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('confidence_override', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_key', name='uq_user_merchant')
    )
    op.create_index(op.f('ix_merchant_mappings_id'), 'merchant_mappings', ['id'], unique=False)
    op.create_table('feedback_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('original_category', sa.String(), nullable=False),
    sa.Column('corrected_category', sa.String(), nullable=False),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_logs_id'), 'feedback_logs', ['id'], unique=False)
    op.add_column('raw_records', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('raw_records', sa.Column('raw_data', sa.String(), nullable=True))
    op.add_column('raw_records', sa.Column('parsed_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'raw_records', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('sub_category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('bank', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('vpa', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('account_ref', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('raw_sms', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('net_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_refund', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_cashback', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_income', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_transfer', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('uploaded_files', sa.Column('s3_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('shopping_behavior', sa.String(), nullable=True))
    op.add_column('users', sa.Column('food_habit', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'food_habit')
    op.drop_column('users', 'shopping_behavior')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone')
    op.drop_column('uploaded_files', 's3_key')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'tags')
    op.drop_column('transactions', 'is_transfer')
    op.drop_column('transactions', 'is_income')
    op.drop_column('transactions', 'is_cashback')
    op.drop_column('transactions', 'is_refund')
    op.drop_column('transactions', 'is_recurring')
    op.drop_column('transactions', 'net_amount')
    op.drop_column('transactions', 'review_status')
    op.drop_column('transactions', 'confidence')
    op.drop_column('transactions', 'raw_sms')
    op.drop_column('transactions', 'account_ref')
    op.drop_column('transactions', 'vpa')
    op.drop_column('transactions', 'bank')
    op.drop_column('transactions', 'sub_category')
    op.drop_column('transactions', 'currency')
    op.drop_constraint(None, 'raw_records', type_='foreignkey')
    op.drop_column('raw_records', 'parsed_status')
    op.drop_column('raw_records', 'raw_data')
    op.drop_column('raw_records', 'user_id')
    op.drop_index(op.f('ix_feedback_logs_id'), table_name='feedback_logs')
    op.drop_table('feedback_logs')
    op.drop_index(op.f('ix_merchant_mappings_id'), table_name='merchant_mappings')
    op.drop_table('merchant_mappings')
    # ### end Alembic commands ###
