"""phase0_schema_expansion

Revision ID: 83ff3c53dab0
Revises: 56d093b8c7b2
Create Date: 2026-04-29 11:00:36.279947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ff3c53dab0'
down_revision: Union[str, Sequence[str], None] = '56d093b8c7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feedback_logs', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_feedback_logs_user_id'), 'feedback_logs', ['user_id'], unique=False)
    op.alter_column('merchant_mappings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('merchant_mappings', 'sub_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_merchant_mappings_user_id'), 'merchant_mappings', ['user_id'], unique=False)
    op.create_index(op.f('ix_raw_records_user_id'), 'raw_records', ['user_id'], unique=False)
    op.add_column('recommendations', sa.Column('why', sa.String(), nullable=True))
    op.alter_column('recommendations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('tx_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_wallet_load', sa.Boolean(), nullable=True))
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.alter_column('uploaded_files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'food_habit')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'shopping_behavior')
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('shopping_behavior', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('food_habit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.alter_column('uploaded_files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'is_wallet_load')
    op.drop_column('transactions', 'tx_type')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.alter_column('recommendations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('recommendations', 'why')
    op.drop_index(op.f('ix_raw_records_user_id'), table_name='raw_records')
    op.drop_index(op.f('ix_merchant_mappings_user_id'), table_name='merchant_mappings')
    op.alter_column('merchant_mappings', 'sub_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('merchant_mappings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_feedback_logs_user_id'), table_name='feedback_logs')
    op.alter_column('feedback_logs', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feedback_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
